/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesInvestmentBankingRouteImport } from './routes/services/investment-banking'
import { Route as ServicesFinancingRouteImport } from './routes/services/financing'
import { Route as ServicesExecutionTradingRouteImport } from './routes/services/execution-trading'
import { Route as ServicesClearingRouteImport } from './routes/services/clearing'
import { Route as ServicesActiveTradingRouteImport } from './routes/services/active-trading'
import { Route as LegalSecurityRouteImport } from './routes/legal/security'
import { Route as LegalRegulatoryDisclosuresRouteImport } from './routes/legal/regulatory-disclosures'
import { Route as LegalPrivacyNoticeRouteImport } from './routes/legal/privacy-notice'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesInvestmentBankingRoute =
  ServicesInvestmentBankingRouteImport.update({
    id: '/services/investment-banking',
    path: '/services/investment-banking',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesFinancingRoute = ServicesFinancingRouteImport.update({
  id: '/services/financing',
  path: '/services/financing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesExecutionTradingRoute =
  ServicesExecutionTradingRouteImport.update({
    id: '/services/execution-trading',
    path: '/services/execution-trading',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesClearingRoute = ServicesClearingRouteImport.update({
  id: '/services/clearing',
  path: '/services/clearing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesActiveTradingRoute = ServicesActiveTradingRouteImport.update({
  id: '/services/active-trading',
  path: '/services/active-trading',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSecurityRoute = LegalSecurityRouteImport.update({
  id: '/legal/security',
  path: '/legal/security',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRegulatoryDisclosuresRoute =
  LegalRegulatoryDisclosuresRouteImport.update({
    id: '/legal/regulatory-disclosures',
    path: '/legal/regulatory-disclosures',
    getParentRoute: () => rootRouteImport,
  } as any)
const LegalPrivacyNoticeRoute = LegalPrivacyNoticeRouteImport.update({
  id: '/legal/privacy-notice',
  path: '/legal/privacy-notice',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/news': typeof NewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/legal/privacy-notice': typeof LegalPrivacyNoticeRoute
  '/legal/regulatory-disclosures': typeof LegalRegulatoryDisclosuresRoute
  '/legal/security': typeof LegalSecurityRoute
  '/services/active-trading': typeof ServicesActiveTradingRoute
  '/services/clearing': typeof ServicesClearingRoute
  '/services/execution-trading': typeof ServicesExecutionTradingRoute
  '/services/financing': typeof ServicesFinancingRoute
  '/services/investment-banking': typeof ServicesInvestmentBankingRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/news': typeof NewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/legal/privacy-notice': typeof LegalPrivacyNoticeRoute
  '/legal/regulatory-disclosures': typeof LegalRegulatoryDisclosuresRoute
  '/legal/security': typeof LegalSecurityRoute
  '/services/active-trading': typeof ServicesActiveTradingRoute
  '/services/clearing': typeof ServicesClearingRoute
  '/services/execution-trading': typeof ServicesExecutionTradingRoute
  '/services/financing': typeof ServicesFinancingRoute
  '/services/investment-banking': typeof ServicesInvestmentBankingRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/news': typeof NewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/legal/privacy-notice': typeof LegalPrivacyNoticeRoute
  '/legal/regulatory-disclosures': typeof LegalRegulatoryDisclosuresRoute
  '/legal/security': typeof LegalSecurityRoute
  '/services/active-trading': typeof ServicesActiveTradingRoute
  '/services/clearing': typeof ServicesClearingRoute
  '/services/execution-trading': typeof ServicesExecutionTradingRoute
  '/services/financing': typeof ServicesFinancingRoute
  '/services/investment-banking': typeof ServicesInvestmentBankingRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/clients'
    | '/contact'
    | '/news'
    | '/sitemap.xml'
    | '/studio'
    | '/legal/privacy-notice'
    | '/legal/regulatory-disclosures'
    | '/legal/security'
    | '/services/active-trading'
    | '/services/clearing'
    | '/services/execution-trading'
    | '/services/financing'
    | '/services/investment-banking'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/clients'
    | '/contact'
    | '/news'
    | '/sitemap.xml'
    | '/studio'
    | '/legal/privacy-notice'
    | '/legal/regulatory-disclosures'
    | '/legal/security'
    | '/services/active-trading'
    | '/services/clearing'
    | '/services/execution-trading'
    | '/services/financing'
    | '/services/investment-banking'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/clients'
    | '/contact'
    | '/news'
    | '/sitemap.xml'
    | '/studio'
    | '/legal/privacy-notice'
    | '/legal/regulatory-disclosures'
    | '/legal/security'
    | '/services/active-trading'
    | '/services/clearing'
    | '/services/execution-trading'
    | '/services/financing'
    | '/services/investment-banking'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  ClientsRoute: typeof ClientsRoute
  ContactRoute: typeof ContactRoute
  NewsRoute: typeof NewsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudioRoute: typeof StudioRoute
  LegalPrivacyNoticeRoute: typeof LegalPrivacyNoticeRoute
  LegalRegulatoryDisclosuresRoute: typeof LegalRegulatoryDisclosuresRoute
  LegalSecurityRoute: typeof LegalSecurityRoute
  ServicesActiveTradingRoute: typeof ServicesActiveTradingRoute
  ServicesClearingRoute: typeof ServicesClearingRoute
  ServicesExecutionTradingRoute: typeof ServicesExecutionTradingRoute
  ServicesFinancingRoute: typeof ServicesFinancingRoute
  ServicesInvestmentBankingRoute: typeof ServicesInvestmentBankingRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/investment-banking': {
      id: '/services/investment-banking'
      path: '/services/investment-banking'
      fullPath: '/services/investment-banking'
      preLoaderRoute: typeof ServicesInvestmentBankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/financing': {
      id: '/services/financing'
      path: '/services/financing'
      fullPath: '/services/financing'
      preLoaderRoute: typeof ServicesFinancingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/execution-trading': {
      id: '/services/execution-trading'
      path: '/services/execution-trading'
      fullPath: '/services/execution-trading'
      preLoaderRoute: typeof ServicesExecutionTradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/clearing': {
      id: '/services/clearing'
      path: '/services/clearing'
      fullPath: '/services/clearing'
      preLoaderRoute: typeof ServicesClearingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/active-trading': {
      id: '/services/active-trading'
      path: '/services/active-trading'
      fullPath: '/services/active-trading'
      preLoaderRoute: typeof ServicesActiveTradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/security': {
      id: '/legal/security'
      path: '/legal/security'
      fullPath: '/legal/security'
      preLoaderRoute: typeof LegalSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/regulatory-disclosures': {
      id: '/legal/regulatory-disclosures'
      path: '/legal/regulatory-disclosures'
      fullPath: '/legal/regulatory-disclosures'
      preLoaderRoute: typeof LegalRegulatoryDisclosuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy-notice': {
      id: '/legal/privacy-notice'
      path: '/legal/privacy-notice'
      fullPath: '/legal/privacy-notice'
      preLoaderRoute: typeof LegalPrivacyNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  ClientsRoute: ClientsRoute,
  ContactRoute: ContactRoute,
  NewsRoute: NewsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudioRoute: StudioRoute,
  LegalPrivacyNoticeRoute: LegalPrivacyNoticeRoute,
  LegalRegulatoryDisclosuresRoute: LegalRegulatoryDisclosuresRoute,
  LegalSecurityRoute: LegalSecurityRoute,
  ServicesActiveTradingRoute: ServicesActiveTradingRoute,
  ServicesClearingRoute: ServicesClearingRoute,
  ServicesExecutionTradingRoute: ServicesExecutionTradingRoute,
  ServicesFinancingRoute: ServicesFinancingRoute,
  ServicesInvestmentBankingRoute: ServicesInvestmentBankingRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
